CONFIG_ZMK_HID_REPORT_TYPE_NKRO=n
CONFIG_ZMK_HID_REPORT_TYPE_HKRO=y
CONFIG_ZMK_HID_KEYBOARD_REPORT_SIZE=6
CONFIG_ZMK_REMOTE_HID_BRIDGE=y
CONFIG_ZMK_REMOTE_HID_BRIDGE_LEASE_MS=4000
CONFIG_ZMK_REMOTE_HID_BRIDGE_CONSUMER=n
