manifest:
  remotes:
    - name: zmk-fork
      url-base: https://github.com/vanilla-tom
  projects:
    - name: zmk
      remote: zmk-fork
      revision: 808ee78da93461da0b254585442716ce6c6e4a79
      import: app/west.yml
  self:
    path: config